# fly.toml app configuration file generated for spacy-misty-glitter-4206 on 2024-10-25T11:16:18-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'spacy-misty-glitter-4206'
primary_region = 'ewr'

[build]

[http_service]
  internal_port = 5001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
